<?php
/** @package Santis::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("SliderMap.php");

/**
 * SliderDAO provides object-oriented access to the slider table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Santis::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class SliderDAO extends Phreezable
{
	/** @var int */
	public $IdSlider;

	/** @var string */
	public $ImgFondo;

	/** @var string */
	public $ImgProducto;

	/** @var string */
	public $NombreProducto;

	/** @var string */
	public $DescSupProd;

	/** @var string */
	public $DescInfProd;

	/** @var string */
	public $Link;

	/** @var int */
	public $Orden;

	/** @var int */
	public $Habilitado;



}
?>