<?php
/** @package Santis::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("SliderTaMap.php");

/**
 * SliderTaDAO provides object-oriented access to the slider_ta table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Santis::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class SliderTaDAO extends Phreezable
{
	/** @var int */
	public $IdSliderTa;

	/** @var string */
	public $ImgProducto;

	/** @var string */
	public $TitProducto;

	/** @var string */
	public $TitProp1;

	/** @var string */
	public $DescProp1;

	/** @var string */
	public $TitProp2;

	/** @var string */
	public $DescProp2;

	/** @var string */
	public $TitProp3;

	/** @var string */
	public $DescProp3;

	/** @var string */
	public $Link;

	/** @var int */
	public $Orden;

	/** @var int */
	public $Habilitado;



}
?>